language: node_js

node_js:
  - "10.13.0"


matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
  - name: "MacOS"
    os: osx


before_install:
  - npm conf set strict-ssl false
  - npm install -g npm@6.4.1


script:
  - cd test
  - npm i
  - npm test
  - cd ..
