language: node_js
node_js:
  - "10.16.1"

install:
  - cd test
  - npm i

matrix:
  include:
  - name: "Linux Test"
    os: linux
    dist: xenial
    sudo: false
  - name: "OSX Test"
    os: osx
  - name: "Linux Build"
    os: linux
    dist: xenial
    sudo: false
    if: commit_message =~ /^:hammer:/
    env:
    - ISBUILD=true
    - SYSNAME=Linux
    install:
      - cd src
    script:
      - npm i
  - name: "OSX Build"
    os: osx
    if: commit_message =~ /^:hammer:/
    env:
    - ISBUILD=true
    - SYSNAME=OSX
    install:
      - cd src
    script:
      - npm i


deploy:
  on:
    all_branches: true
    condition: $ISBUILD = true
  provider: releases
  name: "Binary for $SYSNAME"
  body: $TRAVIS_COMMIT_MESSAGE
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  overwrite: true
  draft: true
  file:
    - "src/build/Release/image.node"
