dist: trusty
sudo: false

language: node_js

node_js:
  - "10.13.0"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6


env:
  - GCC_EVAL="CC=gcc-6 && CXX=g++-6"


before_install:
  - eval "${GCC_EVAL}"
  - gcc -v && g++ -v && cmake --version
  - npm conf set strict-ssl false
  - npm install -g npm@6.4.1


install:
  - cd test
  - npm i
  - cd ..


script:
  - cd test
  - npm test
  - cd ..
  
