language: node_js

node_js:
  - "10.13.0"


matrix:
  include:
  # - name: "Linux"
  #   os: linux
  #   dist: xenial
  #   sudo: false
  - name: "MacOS"
    os: osx


install:
  - cd test
  - npm i


script:
  - otool -hV node_modules/deps-freeimage-raub/bin-mac64/libfreeimage-3.17.0.dylib-x86_64 || echo NO
  - export LD_LIBRARY_PATH=node_modules/deps-freeimage-raub/bin-mac64
  - export DYLD_LIBRARY_PATH=node_modules/deps-freeimage-raub/bin-mac64
  - npm test
  - cd ..
