dist: xenial
sudo: false

language: node_js

node_js:
  - "10.13.0"


before_install:
  - npm conf set strict-ssl false
  - npm install -g npm@6.4.1


install:
  - cd test
  - npm i
  - cd ..


script:
  - cd test
  - npm test
  - cd ..
