language: node_js

node_js:
  - "10.13.0"


matrix:
  include:
  - name: "Linux"
    os: linux
    dist: xenial
    sudo: false
  - name: "MacOS"
    os: osx


before_install:
  - npm conf set strict-ssl false
  - npm install -g npm@6.4.1


script:
  - cd test
  - npm i
  - ls
  - ls node_modules || echo NO
  - ls node_modules/deps-freeimage-raub || echo NO
  - ls node_modules/deps-freeimage-raub/bin-mac64 || echo NO
  - otool -hV node_modules/deps-freeimage-raub/bin-mac64/freeimage_flat.dylib || echo NO
  - npm test
  - cd ..
