name: Validate
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-20.04

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Run ESLint
        run: npm run eslint

  unit-tests:
    name: Unit Tests
    strategy:
        matrix:
          os: [ubuntu-20.04, windows-2022, macos-11, [self-hosted, linux, ARM64]]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'npm'

      - name: Install Modules
        run: npm ci

      - name: Build Current Binary
        run: npm run build-all

      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2022'
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Run Unit Tests - Windows
        if: matrix.os == 'windows-2022'
        shell: cmd
        run: npm run test-ci

      # - name: Run Unit Tests - Windows
      #   if: matrix.os == 'windows-2022'
      #   shell: cmd
      #   run: cd test && node depends && cd ..

      # - name: Store Dep Trace
      #   if: matrix.os == 'windows-2022'
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     draft: true
      #     tag_name: ${{ steps.package-version.outputs.version }}
      #     name: Release ${{ steps.package-version.outputs.version }}
      #     files: test/dep.txt

      - name: Run Unit Tests - Unix
        if: matrix.os != 'windows-2022'
        run: npm run test-ci
